server:
  port: 31001

spring:
  application:
    name: xc-service-manager-cms
  data:
    mongodb:
      uri: mongodb://root:897570@localhost:27017
      database: xc_cms
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false